import assert from 'node:assert';
import { parseMessages, classify, alertState, DEFAULT_PLACES } from './index.js';
const places = DEFAULT_PLACES.split(',').map(s => s.toLowerCase());
const msg = (post, t, text) => `<div class="tgme_widget_message_wrap js-widget_message_wrap"><div class="tgme_widget_message" data-post="${post}"><div class="tgme_widget_message_text js-message_text" dir="auto">${text}</div><a class="tgme_widget_message_date"><time datetime="${t}" class="time">x</time></a></div></div>`;
const m = parseMessages(msg('a/1', '2026-09-30T17:00:00+00:00', '🔴 Повітряна тривога в Житомирська область<br/>#Житомирська_область') + msg('a/2', '2026-09-30T17:30:00+00:00', '🟢 Відбій тривоги в Житомирська область'));
assert.equal(m.length, 2); assert.equal(m[0].post, 'a/1'); assert.equal(m[1].ts, Date.parse('2026-09-30T17:30:00Z'));
assert.equal(alertState(m[0].text, places), 'on'); assert.equal(alertState(m[1].text, places), 'off');
assert.equal(alertState('Повітряна тривога в Київська область', places), null);
assert.equal(classify('Шахеди курсом на Житомир з півночі', places), 'course');
assert.equal(classify('У Бердичеві чути вибухи, працює ППО', places), 'pvo');
assert.equal(classify('Приліт у Коростені, пошкоджено будинок', places), 'hit');
assert.equal(classify('Шахеди на Київ', places), null);
console.log('ok');
